		CREATE USER 'lsi'@'localhost' IDENTIFIED BY 'lsi';
		GRANT CREATE, ALTER, DROP, INSERT, UPDATE, INDEX, DELETE, SELECT,
		    REFERENCES, RELOAD ON *.* TO 'lsi'@'localhost' WITH GRANT OPTION;
		FLUSH PRIVILEGES;
